spring:
    application:
        name: api-gate
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/ag_gate?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.github.wxiaoqi.security.api.gate.mapper
    xmlLocation: classpath:mapper/**/*.xml
server:
    port: 8767 #启动端口

#zuul:
#  routes:
#    uc:
#      path: /admin/**
#      serviceId: admin-back



ribbon:
  eureka:
    enabled: true


eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: admin
        password: admin
        role: USER

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
# JWT
jwt:
  header: access-token
  secret: mySecret
  expiration: 7200
  tokenHead: ApiGateToken


gate:
  client:
    clientId: admin-api-gate
    secret: $2a$12$AeVHvq5Q6kv54uqmpGXo2OnS8GaEB.5CffhxU0.THi3aHWlvOAhoO
    authHeader: access-token
    authHost: http://localhost:8765/api
    tokenHead: ApiGateToken