spring:
    application:
        name: ace-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    redis:
        database: 1
        host: 127.0.0.1
        pool:
            max-active: 20
server:
    port: 8765 #启动端口
#
zuul:
#  #prefix: /techouse #为zuul设置一个公共的前缀
#  #ignoredServices: '*'
  routes:
    back:
      path: /api/**

ribbon:
  eureka:
    enabled: true

#ace-monitor:
#  ribbon:
#    listOfServers: 127.0.0.1:8764

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: admin
        password: admin
        role: USER

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

gate:
  ignore:
    startWith: /back/menu/user,/admin/index,/admin/about
    contain: .
  oauth:
    prefix: /api
#    authorizationUrl: